# Template: Python / FastAPI fake server.
#
# This is a STARTER. Adapt to the surfaces you discovered.
# Do NOT copy verbatim — the routes, schemas, and transforms must come from
# the real application.
#
# Conventions:
#   - Each route group lives in its own module under ./routes/.
#   - Each transform lives in its own module under ./transforms/ if non-trivial.
#   - Stateful-lite state lives in ./state.py (a tiny in-memory store).
#   - The admin /__reset endpoint wipes all state — tests call it between cases.

import os
from datetime import datetime, timezone
from fastapi import FastAPI, Request
from fastapi.responses import JSONResponse

from . import state

app = FastAPI(
    title="orders-service-fake",
    version="0.1.0",
    description="Fake of the orders-service. Generated by Atomic (generate-fake skill).",
)


# --- Health & admin ---------------------------------------------------------

@app.get("/health")
def health():
    return {"status": "ok", "fake": True}


@app.post("/__reset", status_code=204)
def admin_reset():
    """Wipe in-memory state. Tests call this between cases."""
    state.reset()
    return JSONResponse(status_code=204, content=None)


# --- Example: canned response ----------------------------------------------

@app.get("/version")
def version():
    return {"version": "1.0.0-fake"}


# --- Example: transform (echo + synthesise) --------------------------------

@app.get("/users/{user_id}")
def get_user(user_id: str):
    # Transform: echo the id back inside a stable shape.
    return {
        "id": user_id,
        "email": f"{user_id}@example.com",
        "created_at": "2026-01-01T00:00:00Z",
    }


# --- Example: stateful-lite (write then read) ------------------------------

@app.post("/orders")
async def create_order(request: Request):
    body = await request.json()
    order_id = f"ord_{state.next_seq('orders'):06d}"
    record = {
        **body,
        "id": order_id,
        "status": "accepted",
        "created_at": "2026-01-01T00:00:00Z",
    }
    state.put("orders", order_id, record)
    return record


@app.get("/orders/{order_id}")
def get_order(order_id: str):
    found = state.get("orders", order_id)
    if not found:
        return JSONResponse(status_code=404, content={"error": "not_found"})
    return found


# --- Example: error envelope -----------------------------------------------

@app.exception_handler(Exception)
async def all_exceptions(request: Request, exc: Exception):
    # Match the real app's error envelope if it has one.
    return JSONResponse(
        status_code=500,
        content={"error": "internal_error", "message": str(exc)},
    )


if __name__ == "__main__":
    import uvicorn
    port = int(os.environ.get("FAKE_PORT", "8000"))
    uvicorn.run(app, host="0.0.0.0", port=port)
